name: CI/CD Pipeline for Initiate Payment API

on:
  push:
    paths:
      - 'initiate-payment/**'
  pull_request:
    paths:
      - 'initiate-payment/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Build library module
        run: mvn -f library/pom.xml clean package


      - name: Build initiate-payment module
        run: mvn -f initiate-payment/pom.xml clean package

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Logs into Docker Hub using credentials stored in GitHub Secrets, allowing for subsequent image push actions.

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push-action@v5
        with:
          image: nd2k/initiate-payment
          tags: latest
          registry: docker.io
          dockerfile: initiate-payment/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}